pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "AndroidNewbieGuidance"
include ':app'
include ':kn-shared'
include ':foundation'
include ':chapters'
include ':chapters:chapter1_kotlin'
include ':chapters:chapter2_android_and_jvm'
include ':chapters:chapter3_compose_ui'
